### ISSUE TITLE
using google spreadsheet --> bertha --> json feed as a source for carousel

### ISSUE THREAD

**Issue by railsagainstignorance** [ftlabs/screens-carousel#5]
IMHO it would unleash things somewhat if we did the following to carousels:
1) keep the standard/current static list of urls, or
2) dynamically taking urls from a json feed (formatted a la Bertha)

The json feed would be polled at the end of each cycle in case it has changed.

The spreadsheet would provide a CMS, ACL, changelog etc for the contents of the carousel, and have the same json-fed carousel in multiple screens would keep them in sync, content-wise, with less admin overhead.

It would support ft-wide competitions for putting content up on the display screens.

Via the json feed, in addition to a simple url, I would suggest 
- optional markdown text for each item, which could be used to introduce an entry
- optional duration per item

and set across the whole json feed
- a default duration per item
- optional default markdown for an intro
- optional default markdown for all items

**Comment by JakeChampion** [comment]
As this is a new content creation idea, I would suggest it being a separate project.

The code-base is getting rather large, it would simplify things a great deal if we could split out the content creation services from the distribution service.

**Comment by railsagainstignorance** [comment]
yes, its in the project list. Just thought it worth adding here in case a refactoring made it simple

**Comment by JakeChampion** [comment]
I think it would make it simpler if we created a registry content-creation services. 

I think this issue could be closed and a new issue created to discuss the separation of content-creation services from the code-base.
